import { PintAECheck } from '@/types/pintAE';

// UAE UC1 Standard Tax Invoice Check Pack
// 34 checks aligned with PINT-AE / UAE MoF Data Dictionary

export const UAE_UC1_CHECK_PACK: PintAECheck[] = [
  // ============ Header Presence & Format Checks (001-011) ============
  {
    check_id: 'UAE-UC1-CHK-001',
    check_name: 'Invoice Number Present',
    description: 'Validates that invoice number (IBT-001) is present',
    scope: 'Header',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-001'],
    mof_rule_reference: 'BR-01',
    pass_condition: 'Invoice number field is not empty',
    fail_condition: 'Invoice number field is empty or missing',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Ensure every invoice has a unique invoice number assigned before submission',
    evidence_required: 'Invoice document or source system export showing invoice number',
    is_enabled: true,
    parameters: { field: 'invoice_number' },
  },
  {
    check_id: 'UAE-UC1-CHK-002',
    check_name: 'Invoice Issue Date Present',
    description: 'Validates that invoice issue date (IBT-002) is present',
    scope: 'Header',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-002'],
    mof_rule_reference: 'BR-02',
    pass_condition: 'Issue date field is not empty',
    fail_condition: 'Issue date field is empty or missing',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Populate the issue date field with the actual invoice date in YYYY-MM-DD format',
    evidence_required: 'Source document showing invoice date',
    is_enabled: true,
    parameters: { field: 'issue_date' },
  },
  {
    check_id: 'UAE-UC1-CHK-003',
    check_name: 'Invoice Issue Date Format',
    description: 'Validates issue date is in YYYY-MM-DD format (IBT-002)',
    scope: 'Header',
    rule_type: 'Format',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-002'],
    mof_rule_reference: 'BR-02-FORMAT',
    pass_condition: 'Issue date matches YYYY-MM-DD pattern',
    fail_condition: 'Issue date does not match required format',
    owner_team_default: 'Client IT',
    suggested_fix: 'Convert date to ISO 8601 format (YYYY-MM-DD) before submission',
    evidence_required: 'System configuration showing date format settings',
    is_enabled: true,
    parameters: { field: 'issue_date', pattern: '^\\d{4}-\\d{2}-\\d{2}$' },
  },
  {
    check_id: 'UAE-UC1-CHK-004',
    check_name: 'Invoice Type Code Present',
    description: 'Validates invoice type code (IBT-003) is present',
    scope: 'Header',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-003', 'BTUAE-02'],
    mof_rule_reference: 'BR-03',
    pass_condition: 'Invoice type code field is not empty',
    fail_condition: 'Invoice type code is missing',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Specify the invoice type (e.g., 380 for standard invoice, 381 for credit note)',
    evidence_required: 'Invoice classification documentation',
    is_enabled: true,
    parameters: { field: 'invoice_type' },
  },
  {
    check_id: 'UAE-UC1-CHK-005',
    check_name: 'Invoice Currency Present',
    description: 'Validates document currency code (IBT-005) is present',
    scope: 'Header',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-005'],
    mof_rule_reference: 'BR-04',
    pass_condition: 'Currency code field is not empty',
    fail_condition: 'Currency code is missing',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Specify the transaction currency using ISO 4217 alpha-3 code',
    evidence_required: 'Invoice document showing currency',
    is_enabled: true,
    parameters: { field: 'currency' },
  },
  {
    check_id: 'UAE-UC1-CHK-006',
    check_name: 'Invoice Currency ISO Format',
    description: 'Validates currency is ISO 4217 alpha-3 format (IBT-005)',
    scope: 'Header',
    rule_type: 'CodeList',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-005'],
    mof_rule_reference: 'BR-04-CL',
    pass_condition: 'Currency exists in official ISO4217 codelist',
    fail_condition: 'Currency value is not in official ISO4217 codelist',
    owner_team_default: 'Client IT',
    suggested_fix: 'Use standard ISO 4217 codes (e.g., AED, USD, EUR)',
    evidence_required: 'Currency master data configuration',
    is_enabled: true,
    parameters: { field: 'currency', codelist: 'ISO4217' },
  },
  {
    check_id: 'UAE-UC1-CHK-007',
    check_name: 'Tax Accounting Currency AED Rule',
    description: 'Validates tax accounting basis currency is AED (BTUAE-001)',
    scope: 'Header',
    rule_type: 'CodeList',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-006', 'BTUAE-001'],
    mof_rule_reference: 'BTUAE-001',
    pass_condition: 'Tax amounts are calculated/reported in AED',
    fail_condition: 'Non-AED tax accounting without proper FX conversion',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Ensure tax calculations use AED as the tax accounting currency per UAE VAT law',
    evidence_required: 'Tax calculation documentation showing AED basis',
    is_enabled: true,
    parameters: { tax_currency: 'AED' },
  },
  {
    check_id: 'UAE-UC1-CHK-008',
    check_name: 'FX Rate Required When Non-AED',
    description: 'Validates FX rate is provided when invoice currency is not AED',
    scope: 'Header',
    rule_type: 'Dependency',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-005', 'IBT-007', 'BTUAE-002'],
    mof_rule_reference: 'BTUAE-002',
    pass_condition: 'FX rate is present when currency != AED, or currency is AED',
    fail_condition: 'Non-AED currency without FX rate',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Provide the exchange rate to AED when invoicing in foreign currency',
    evidence_required: 'FX rate source and calculation documentation',
    is_enabled: true,
    parameters: { currency_field: 'currency', fx_field: 'fx_rate', base_currency: 'AED' },
  },
  {
    check_id: 'UAE-UC1-CHK-009',
    check_name: 'Payment Due Date Required if Amount Due > 0',
    description: 'Validates payment due date is present when amount is due',
    scope: 'Header',
    rule_type: 'Dependency',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-009', 'IBT-081'],
    mof_rule_reference: 'BR-CO-25',
    pass_condition: 'Due date present when amount due > 0, or no amount due',
    fail_condition: 'Amount due exists without payment due date',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Add payment due date when there is an outstanding amount',
    evidence_required: 'Payment terms documentation',
    is_enabled: true,
    parameters: { amount_field: 'amount_due', date_field: 'payment_due_date' },
  },
  {
    check_id: 'UAE-UC1-CHK-010',
    check_name: 'Specification Identifier Correct Prefix',
    description: 'Validates specification ID starts with urn:peppol:pint prefix',
    scope: 'Header',
    rule_type: 'Format',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-024'],
    mof_rule_reference: 'BR-01-PINT',
    pass_condition: 'Specification ID contains PINT-AE identifier',
    fail_condition: 'Missing or incorrect specification identifier',
    owner_team_default: 'Client IT',
    suggested_fix: 'Set specification identifier to urn:peppol:pint:billing-1@uae-1',
    evidence_required: 'System integration configuration',
    is_enabled: true,
    parameters: { field: 'spec_id', pattern: 'urn:peppol:pint' },
  },
  {
    check_id: 'UAE-UC1-CHK-011',
    check_name: 'Business Process Type Correct',
    description: 'Validates business process type matches expected value',
    scope: 'Header',
    rule_type: 'CodeList',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-023'],
    mof_rule_reference: 'BR-02-PINT',
    pass_condition: 'Business process type is valid PINT process',
    fail_condition: 'Invalid or missing business process type',
    owner_team_default: 'Client IT',
    suggested_fix: 'Set business process to urn:peppol:bis:billing',
    evidence_required: 'Integration specification document',
    is_enabled: true,
    parameters: { field: 'business_process', allowed_values: ['urn:peppol:bis:billing'] },
  },

  // ============ Seller Party Checks (012-016) ============
  {
    check_id: 'UAE-UC1-CHK-012',
    check_name: 'Seller Name Present',
    description: 'Validates seller trading name (IBT-027) is present',
    scope: 'Party',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-027'],
    mof_rule_reference: 'BR-05',
    pass_condition: 'Seller name field is not empty',
    fail_condition: 'Seller name is missing',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Populate seller name from company master data',
    evidence_required: 'Trade license or company registration',
    is_enabled: true,
    parameters: { field: 'seller_name' },
  },
  {
    check_id: 'UAE-UC1-CHK-013',
    check_name: 'Seller TRN Pattern Valid',
    description: 'Validates Seller TRN matches UAE 15-digit format (IBT-031)',
    scope: 'Party',
    rule_type: 'Format',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-031', 'IBT-031-1'],
    mof_rule_reference: 'BTUAE-003',
    pass_condition: 'Seller TRN is exactly 15 digits',
    fail_condition: 'Seller TRN format is invalid',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Correct the TRN to 15 digits as registered with FTA',
    evidence_required: 'FTA TRN certificate',
    is_enabled: true,
    parameters: { field: 'seller_trn', pattern: '^\\d{15}$' },
  },
  {
    check_id: 'UAE-UC1-CHK-014',
    check_name: 'Seller Electronic Address Present',
    description: 'Validates seller electronic address endpoint (IBT-034)',
    scope: 'Party',
    rule_type: 'Presence',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-034', 'IBT-034-1'],
    mof_rule_reference: 'BR-62',
    pass_condition: 'Seller endpoint ID is present',
    fail_condition: 'Seller electronic address is missing',
    owner_team_default: 'Client IT',
    suggested_fix: 'Configure seller PEPPOL participant ID or email endpoint',
    evidence_required: 'PEPPOL registration or endpoint configuration',
    is_enabled: true,
    parameters: { field: 'seller_electronic_address' },
  },
  {
    check_id: 'UAE-UC1-CHK-015',
    check_name: 'Seller Address Mandatory Fields',
    description: 'Validates seller address has required components (IBT-035 to IBT-040)',
    scope: 'Party',
    rule_type: 'Presence',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-030', 'BTUAE-15', 'IBT-035', 'IBT-037', 'IBT-040'],
    mof_rule_reference: 'BR-08',
    pass_condition: 'Seller street, city, and country code are present',
    fail_condition: 'Seller address is incomplete',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Complete seller address with street, city, and country code (AE)',
    evidence_required: 'Company address documentation',
    is_enabled: true,
    parameters: { fields: ['seller_address', 'seller_city', 'seller_country'] },
  },
  {
    check_id: 'UAE-UC1-CHK-016',
    check_name: 'UAE Subdivision Code Valid',
    description: 'Validates UAE emirate/subdivision code (IBT-039)',
    scope: 'Party',
    rule_type: 'CodeList',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-039', 'BTUAE-004'],
    mof_rule_reference: 'BTUAE-004',
    pass_condition: 'Subdivision code is valid UAE emirate code',
    fail_condition: 'Invalid UAE emirate/subdivision code',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Use valid UAE emirate code (AE-AZ, AE-AJ, AE-FU, AE-SH, AE-DU, AE-RK, AE-UQ)',
    evidence_required: 'Address verification',
    is_enabled: true,
    parameters: { 
      field: 'seller_subdivision',
      allowed_values: ['AE-AZ', 'AE-AJ', 'AE-FU', 'AE-SH', 'AE-DU', 'AE-RK', 'AE-UQ']
    },
  },

  // ============ Buyer Party Checks (017-020) ============
  {
    check_id: 'UAE-UC1-CHK-017',
    check_name: 'Buyer Name Present',
    description: 'Validates buyer name (IBT-044) is present',
    scope: 'Party',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-044'],
    mof_rule_reference: 'BR-07',
    pass_condition: 'Buyer name field is not empty',
    fail_condition: 'Buyer name is missing',
    owner_team_default: 'Buyer-side',
    suggested_fix: 'Obtain and populate buyer legal or trading name',
    evidence_required: 'Customer master data or purchase order',
    is_enabled: true,
    parameters: { field: 'buyer_name' },
  },
  {
    check_id: 'UAE-UC1-CHK-018',
    check_name: 'Buyer TRN Pattern Valid',
    description: 'Validates Buyer TRN matches UAE 15-digit format when present',
    scope: 'Party',
    rule_type: 'Format',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-048', 'IBT-048-1'],
    mof_rule_reference: 'BTUAE-005',
    pass_condition: 'Buyer TRN is exactly 15 digits (when provided)',
    fail_condition: 'Buyer TRN format is invalid',
    owner_team_default: 'Buyer-side',
    suggested_fix: 'Verify buyer TRN with FTA portal or request valid TRN',
    evidence_required: 'Buyer TRN certificate',
    is_enabled: true,
    parameters: { field: 'buyer_trn', pattern: '^\\d{15}$', allow_empty: true },
  },
  {
    check_id: 'UAE-UC1-CHK-019',
    check_name: 'Buyer Electronic Address Present',
    description: 'Validates buyer electronic address endpoint (IBT-049)',
    scope: 'Party',
    rule_type: 'Presence',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-049', 'IBT-049-1'],
    mof_rule_reference: 'BR-63',
    pass_condition: 'Buyer endpoint ID is present',
    fail_condition: 'Buyer electronic address is missing',
    owner_team_default: 'Client IT',
    suggested_fix: 'Configure buyer PEPPOL participant ID or email endpoint',
    evidence_required: 'Buyer registration or contact details',
    is_enabled: true,
    parameters: { field: 'buyer_electronic_address' },
  },
  {
    check_id: 'UAE-UC1-CHK-020',
    check_name: 'Buyer Address Mandatory Fields',
    description: 'Validates buyer address has required components',
    scope: 'Party',
    rule_type: 'Presence',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-050', 'IBT-052', 'IBT-054', 'IBT-055'],
    mof_rule_reference: 'BR-11',
    pass_condition: 'Buyer street, city, and country code are present',
    fail_condition: 'Buyer address is incomplete',
    owner_team_default: 'Buyer-side',
    suggested_fix: 'Complete buyer address fields',
    evidence_required: 'Customer address records',
    is_enabled: true,
    parameters: { fields: ['buyer_address', 'buyer_country'] },
  },

  // ============ Totals & Calculation Checks (021-029) ============
  {
    check_id: 'UAE-UC1-CHK-021',
    check_name: 'Sum of Line Net Amounts Matches Header',
    description: 'Validates sum of line net amounts equals header total (IBT-106)',
    scope: 'Cross',
    rule_type: 'Math',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-106', 'IBT-131'],
    mof_rule_reference: 'BR-CO-10',
    pass_condition: 'Sum of line net amounts = Invoice total net amount (within tolerance)',
    fail_condition: 'Line totals do not sum to header amount',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Reconcile line item amounts with invoice total',
    evidence_required: 'Invoice calculation breakdown',
    is_enabled: true,
    parameters: { tolerance: 0.01 },
  },
  {
    check_id: 'UAE-UC1-CHK-022',
    check_name: 'Total Without Tax Max 2 Decimals',
    description: 'Validates total without tax has max 2 decimal places (IBT-109)',
    scope: 'Header',
    rule_type: 'Format',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-109'],
    mof_rule_reference: 'BR-DEC-12',
    pass_condition: 'Amount has maximum 2 decimal places',
    fail_condition: 'Amount has more than 2 decimal places',
    owner_team_default: 'Client IT',
    suggested_fix: 'Round total amounts to 2 decimal places',
    evidence_required: 'System rounding configuration',
    is_enabled: true,
    parameters: { field: 'total_excl_vat', max_decimals: 2 },
  },
  {
    check_id: 'UAE-UC1-CHK-023',
    check_name: 'Total Tax Max 2 Decimals',
    description: 'Validates total tax amount has max 2 decimal places (IBT-110)',
    scope: 'Header',
    rule_type: 'Format',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-110'],
    mof_rule_reference: 'BR-DEC-13',
    pass_condition: 'Tax amount has maximum 2 decimal places',
    fail_condition: 'Tax amount has more than 2 decimal places',
    owner_team_default: 'Client IT',
    suggested_fix: 'Round tax amounts to 2 decimal places',
    evidence_required: 'Tax calculation settings',
    is_enabled: true,
    parameters: { field: 'vat_total', max_decimals: 2 },
  },
  {
    check_id: 'UAE-UC1-CHK-024',
    check_name: 'Total With Tax Max 2 Decimals',
    description: 'Validates total with tax has max 2 decimal places (IBT-112)',
    scope: 'Header',
    rule_type: 'Format',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-112'],
    mof_rule_reference: 'BR-DEC-14',
    pass_condition: 'Total amount has maximum 2 decimal places',
    fail_condition: 'Total amount has more than 2 decimal places',
    owner_team_default: 'Client IT',
    suggested_fix: 'Round total amounts to 2 decimal places',
    evidence_required: 'Invoice amount rounding logic',
    is_enabled: true,
    parameters: { field: 'total_incl_vat', max_decimals: 2 },
  },
  {
    check_id: 'UAE-UC1-CHK-025',
    check_name: 'Total With Tax = Without Tax + Tax',
    description: 'Validates total_incl_vat = total_excl_vat + vat_total (IBT-112)',
    scope: 'Header',
    rule_type: 'Math',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-109', 'IBT-110', 'IBT-112'],
    mof_rule_reference: 'BR-CO-15',
    pass_condition: 'Total with tax equals sum of net and tax amounts',
    fail_condition: 'Total mismatch: Total != Net + Tax',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Recalculate invoice totals ensuring Total = Net + VAT',
    evidence_required: 'Invoice calculation worksheet',
    is_enabled: true,
    parameters: { tolerance: 0.01 },
  },
  {
    check_id: 'UAE-UC1-CHK-026',
    check_name: 'Amount Due Precision',
    description: 'Validates amount due has proper precision (IBT-115)',
    scope: 'Header',
    rule_type: 'Format',
    severity: 'Low',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-115'],
    mof_rule_reference: 'BR-DEC-18',
    pass_condition: 'Amount due has maximum 2 decimal places',
    fail_condition: 'Amount due precision exceeds 2 decimals',
    owner_team_default: 'Client IT',
    suggested_fix: 'Round amount due to 2 decimal places',
    evidence_required: 'Payment amount calculation',
    is_enabled: true,
    parameters: { field: 'amount_due', max_decimals: 2 },
  },
  {
    check_id: 'UAE-UC1-CHK-027',
    check_name: 'Tax Breakdown Present',
    description: 'Validates at least one VAT breakdown is present (IBG-23)',
    scope: 'Header',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBG-23', 'IBT-116', 'IBT-118'],
    mof_rule_reference: 'BR-CO-18',
    pass_condition: 'At least one tax category breakdown exists',
    fail_condition: 'No tax breakdown information provided',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Add VAT breakdown showing taxable amount and VAT rate per category',
    evidence_required: 'Tax breakdown schedule',
    is_enabled: true,
    parameters: {},
  },
  {
    check_id: 'UAE-UC1-CHK-028',
    check_name: 'Tax Category Tax Amount Formula',
    description: 'Validates tax amount = taxable amount x rate (IBT-117)',
    scope: 'Header',
    rule_type: 'Math',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-116', 'IBT-117', 'IBT-119', 'IBT-151', 'IBT-152', 'BTUAE-08'],
    mof_rule_reference: 'BR-CO-17',
    pass_condition: 'Tax amount = Taxable base x VAT rate (within rounding tolerance)',
    fail_condition: 'Tax calculation does not match formula',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Verify VAT calculation: Tax = Base x Rate',
    evidence_required: 'VAT calculation breakdown',
    is_enabled: true,
    parameters: { tolerance: 0.01 },
  },
  {
    check_id: 'UAE-UC1-CHK-029',
    check_name: 'Tax Total = Sum of Tax Breakdown Amounts',
    description: 'Validates total tax equals sum of all tax category amounts',
    scope: 'Cross',
    rule_type: 'Math',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-110', 'IBT-117'],
    mof_rule_reference: 'BR-CO-14',
    pass_condition: 'Sum of tax breakdown amounts = Total tax amount',
    fail_condition: 'Tax breakdown sum does not equal total',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Reconcile tax breakdown categories with total VAT',
    evidence_required: 'Tax category breakdown vs total reconciliation',
    is_enabled: true,
    parameters: { tolerance: 0.01 },
  },

  // ============ Line Item Checks (030-034) ============
  {
    check_id: 'UAE-UC1-CHK-030',
    check_name: 'Invoice Must Have >=1 Line',
    description: 'Validates invoice has at least one line item (IBG-25)',
    scope: 'Cross',
    rule_type: 'Presence',
    severity: 'Critical',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBG-25'],
    mof_rule_reference: 'BR-16',
    pass_condition: 'Invoice contains one or more line items',
    fail_condition: 'Invoice has no line items',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Add at least one invoice line with item details',
    evidence_required: 'Invoice with line item details',
    is_enabled: true,
    parameters: {},
  },
  {
    check_id: 'UAE-UC1-CHK-031',
    check_name: 'Line Identifier Present',
    description: 'Validates each line has a unique identifier (IBT-126)',
    scope: 'Lines',
    rule_type: 'Presence',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-126'],
    mof_rule_reference: 'BR-21',
    pass_condition: 'Line identifier is present and unique',
    fail_condition: 'Line identifier is missing or duplicated',
    owner_team_default: 'Client IT',
    suggested_fix: 'Assign unique sequential line numbers to each line item',
    evidence_required: 'Line item numbering logic',
    is_enabled: true,
    parameters: { field: 'line_number' },
  },
  {
    check_id: 'UAE-UC1-CHK-032',
    check_name: 'Invoiced Quantity Present',
    description: 'Validates invoiced quantity is present (IBT-129)',
    scope: 'Lines',
    rule_type: 'Presence',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-129', 'IBT-153'],
    mof_rule_reference: 'BR-22',
    pass_condition: 'Quantity field is present and numeric',
    fail_condition: 'Quantity is missing or invalid',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Specify the quantity for each line item',
    evidence_required: 'Delivery note or quantity source',
    is_enabled: true,
    parameters: { field: 'quantity' },
  },
  {
    check_id: 'UAE-UC1-CHK-033',
    check_name: 'Unit of Measure Code Present',
    description: 'Validates unit of measure is specified (IBT-130)',
    scope: 'Lines',
    rule_type: 'Presence',
    severity: 'Medium',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-130', 'IBT-154'],
    mof_rule_reference: 'BR-23',
    pass_condition: 'Unit of measure code is present',
    fail_condition: 'Unit of measure is missing',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Add UN/ECE Recommendation 20 unit code (e.g., EA, KGM, MTR)',
    evidence_required: 'Unit of measure mapping',
    is_enabled: true,
    parameters: { field: 'unit_of_measure' },
  },
  {
    check_id: 'UAE-UC1-CHK-034',
    check_name: 'Line Net Amount Formula',
    description: 'Validates line net = (qty x price) - allowances + charges (IBT-131)',
    scope: 'Lines',
    rule_type: 'Math',
    severity: 'High',
    use_case: 'UC1 Standard Tax Invoice',
    pint_reference_terms: ['IBT-129', 'IBT-131', 'IBT-146', 'IBT-148', 'IBT-149'],
    mof_rule_reference: 'BR-CO-04',
    pass_condition: 'Line net amount = (Quantity x Unit Price) - Discount',
    fail_condition: 'Line net calculation is incorrect',
    owner_team_default: 'Client Finance',
    suggested_fix: 'Verify line calculation: Net = (Qty x Price) - Discount',
    evidence_required: 'Line item calculation breakdown',
    is_enabled: true,
    parameters: { tolerance: 0.01 },
  },
];

export default UAE_UC1_CHECK_PACK;
